// This file is automatically generated by the Cargo Parcel "islands" command for Cargo Load. Do not edit it manually.
import $I0 from "../src/Counter$.tsx";

export default {
  "src/Counter$.tsx": $I0,
}