// This file is automatically generated by the Cargo Parcel "pages" command for Cargo Load. Do not edit it manually.

// Page imports
import * as P0 from "../pages/page.tsx";

// Layout imports
import * as L0 from "../pages/layout.tsx";

export default {
  "/": {
    page: P0,
    layouts: [L0],
  },
};
